"""
VECTOR DATABASE ENGINE
Purpose: Manages the persistent storage and semantic retrieval of job postings.
Functionality:
    - Interface for ChromaDB to store high-dimensional job embeddings.
    - Handles 'Upsert' operations (Insert or Update) to prevent duplicate entries.
    - Manages structured metadata alongside unstructured text for advanced filtering.
    - Performs similarity searches to find the best job matches for a given resume.
"""

import chromadb
from chromadb.config import Settings as ChromaSettings
from src.utils.config import settings
from src.utils.loggers import get_logger
from src.utils.schemas import JobModel
from typing import List, Optional

# Initialize module-level logger
logger = get_logger(__name__)

class JobVectorDB:
    """
    The 'Long-term Memory' of the system. This class wraps ChromaDB operations
    to provide a clean interface for storing and querying job vectors.
    """
    
    def __init__(self):
        """
        Initializes the database connection and ensures the collection exists.
        """
        # 1. Initialize the Persistent Client.
        # This ensures data is saved to the local disk at the path defined in config.
        self.client = chromadb.PersistentClient(path=settings.CHROMA_PATH)
        
        # 2. Get or Create a Collection.
        # We use 'cosine' similarity (hnsw:space) which is ideal for NLP tasks 
        # to measure the semantic angle between vectors.
        self.collection = self.client.get_or_create_collection(
            name="hot_jobs",
            metadata={"hnsw:space": "cosine"} 
        )
        logger.info(f"Connected to ChromaDB at {settings.CHROMA_PATH}")

    def upsert_job(self, job: JobModel, embedding: List[float]):
        """
        Stores or updates a job and its vector in the database.
        
        Args:
            job (JobModel): The validated Pydantic job object containing metadata.
            embedding (List[float]): The numerical vector generated by the Embedder.
        """
        try:
            # Using 'upsert' ensures that if a job ID already exists, 
            # its vector and metadata are refreshed instead of duplicated.
            self.collection.upsert(
                ids=[job.id],
                embeddings=[embedding],
                metadatas=[{
                    "title": job.title,
                    "company": job.company,
                    "location": job.location,
                    "url": str(job.url) if job.url else ""
                }],
                # Storing the description as 'documents' allows us to see the 
                # raw text when we retrieve search results later.
                documents=[job.description] 
            )
            logger.info(f"Upserted job {job.id}: {job.title}")
        except Exception as e:
            logger.error(f"Failed to upsert job {job.id}: {e}")

    def query_jobs(self, query_embedding: List[float], n_results: int = 5):
        """
        Searches for the most semantically similar jobs.
        
        Args:
            query_embedding (List[float]): The vector representation of a resume.
            n_results (int): The number of top matches to return.
            
        Returns:
            dict: The search results including IDs, distances, metadatas, and documents.
        """
        # The query operation finds the 'Nearest Neighbors' in the vector space.
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )
        return results